wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Example_wandb_delimeter_predictions:
        key: Example_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': General trash
          '1': Paper
          '2': Paper pack
          '3': Metal
          '4': Glass
          '5': Plastic
          '6': Styrofoam
          '7': Plastic bag
          '8': Battery
          '9': Clothing
    cli_version: 0.12.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1649383588
    t:
      3:
      - 17
      4: 3.7.11
      5: 0.12.11
      8:
      - 1
      - 5
